POST http://localhost:3000/api/register
Content-Type: application/json

{
  "name": "Leonardo",
  "email": "leonardo.lima@alest.com.br",
  "password": "123"
}
###
GET http://localhost:3000/api/users
###
GET http://localhost:3000/api/users/leonardo.lima@alest.com.br
###
DELETE http://localhost:3000/api/users/leonardo.lima@alest.com.br
###
PUT http://localhost:3000/api/users/leonardo.lima@alest.com.br
Content-Type: application/json

{
  "name": "Leonardo"
}
###
