POST http://localhost:3000/user
Content-Type: application/json

{
  "name": "Elias",
  "email": "eliass@alest.com.br",
  "password": "123"
}
###
GET http://localhost:3000/users
###
GET http://localhost:3000/user/leonardo.lima@alest.com.br

